defaults:
  settings:
    foid_require_airlines: ["2B","5N","7J","7R","8Q","BT","EY","FZ","HR","HY","J2","KC","KK","KR","LY","NN","PC","PS","QN","R2","R3","S7","SZ","U6","UT","VV","Y7","YC","YK","YQ","ZG"]
    remove_duplicate_airlines: false
    max_attempts_cancel_void: 5 # количество раз, которые система пробует отменить бронирование. каждая попытка предваряется sleep(attempt*seconds)
    max_attempts_doc_issuance: 5 # количество раз, которые система пробует выписать билет. каждая попытка предваряется sleep(attempt*seconds)
    max_attempts_pnr_ret: 5 # количество раз, которые система пробует сделать PNRRET. каждая попытка предваряется sleep(attempt*seconds)
    max_attempts_pnr_add: 5 # количество раз, которые система пробует сделать PNRADD. каждая попытка предваряется sleep(attempt*seconds)
    issue_expire: 30 # time in minutes, set TK XL time in minutes before departure
    booking_requests_delay: 2 # время задержки между запросами букинг
    issue_requests_delay: 0 # время задержки между запросами выписки
    fare_rules_paragraphs_to_show: ["PE", "CD"] # PE (16)-penalties, CD (19)-Children discounts
    fare_qualifier_list: ["P", "U"] # список fareQualifier, с которыми попытаются забронироваться